### ISSUE TITLE
CU2CL fails to compile on Linux Mint 18.2/Ubuntu 16.04 due to string literal operator

### ISSUE THREAD

**Issue by s7jones** [vtsynergy/CU2CL#3]
I get the following error when trying to compile:

```
/home/user/CU2CL/cu2cl_libTooling.cpp: In function ‘int main(int, const char**)’:
/home/user/CU2CL/cu2cl_libTooling.cpp:19:2: error: unable to find string literal operator ‘operator""Virginia’ with ‘const char [83]’, ‘long unsigned int’ arguments
  "/* (C) 2010-2017 Virginia Polytechnic Institute & State University (also known as "Virginia Tech"). All Rights Reserved.
  ^
/home/user/CU2CL/cu2cl_libTooling.cpp:4184:19: note: in expansion of macro ‘CU2CL_LICENSE’
  *cu2cl_header << CU2CL_LICENSE;
                   ^
/home/user/CU2CL/cu2cl_libTooling.cpp:19:2: error: unable to find string literal operator ‘operator""Virginia’ with ‘const char [83]’, ‘long unsigned int’ arguments
  "/* (C) 2010-2017 Virginia Polytechnic Institute & State University (also known as "Virginia Tech"). All Rights Reserved.
  ^
/home/user/CU2CL/cu2cl_libTooling.cpp:4185:17: note: in expansion of macro ‘CU2CL_LICENSE’
  *cu2cl_util << CU2CL_LICENSE;
                 ^
/home/user/CU2CL/cu2cl_libTooling.cpp:19:2: error: unable to find string literal operator ‘operator""Virginia’ with ‘const char [83]’, ‘long unsigned int’ arguments
  "/* (C) 2010-2017 Virginia Polytechnic Institute & State University (also known as "Virginia Tech"). All Rights Reserved.
  ^
/home/user/CU2CL/cu2cl_libTooling.cpp:4186:19: note: in expansion of macro ‘CU2CL_LICENSE’
  *cu2cl_kernel << CU2CL_LICENSE;
```

I could fix the issue by replacing the CU2CL_LICENSE with something simple like "License". It looks like what is happening is that the CU2CL_LICENSE macro accidentally has text which is equivalent to a broken C++11 string literal.

I know Ubuntu 16.04 (xenial) is Debian stretch but it appears CU2CL is compilable on 16.04 with only this change made. Thought you might want to be aware.

Thanks,
s7jones.

**Comment by nullsatz** [comment]
You just need to take out the quotes "Virginia Tech" in the first line.

**Comment by strugglingyq** [comment]
I have the same problem,could you please tell me the detail of this problem?

**Comment by mystal** [comment]
Or just escape the quotes:
`\"Virginia Tech\"`

**Comment by psath** [comment]
Fixed by fd3c34908c
